exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('bikes')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('bikes').insert([
        {
          id: 1,
          name: 'BMC-Timemachine-01-Road-One',
          price: 6999,
          launch_date: new Date().toISOString(),
          score: 4.5,
          brand_id: 11,
          model_family: 'Timemachine',
          model_variant: 'Timemachine 01 Road One',
          model_year: 2020,
          brake_type: 'disc',
          image_url:
            '/images/bicycles/bmc_2020_timemachine_road_01_one_pet_red_gol.png',
          drive_train_type: '',
          includes_powermeter: false,
        },

        {
          id: 2,
          name: 'BMC-Teammachine-SLR01-One-Ltd',
          price: 10449,
          launch_date: new Date().toISOString(),
          score: 4,
          brand_id: 11,
          model_family: 'Teammachine',
          model_variant: 'Teammachine SLR 01',
          model_year: 2020,
          brake_type: 'disc',
          image_url:
            '/images/bicycles/teammachine_slr_01_one_ltd_cbn_wht_red.png',
          drive_train_type: 'SRAM Red AXS HRD (48/35T, 10-28), 160mm rotors',
          includes_powermeter: false,
        },

        {
          id: 3,
          name: 'Cannondale_SystemSix_Hi-MOD_DuraAceDi2',
          price: 9500,
          launch_date: new Date().toISOString(),
          score: 4.5,
          brand_id: 3,
          model_family: 'SystemSix',
          model_variant: 'SystemSix_Hi-MOD_Dura_Ace_Di2',
          model_year: 2020,
          brake_type: 'disc',
          image_url:
            '/images/bicycles/Cannondale_SystemSix_Hi-MOD_DuraAceDi2.png',
          drive_train_type: 'Shimano Dura-Ace Di2',
          includes_powermeter: false,
        },

        {
          id: 4,
          name: 'Ribble Endurance SL R Series Disc',
          price: 7999,
          launch_date: new Date().toISOString(),
          score: 4,
          brand_id: 13,
          model_family: 'Endurance SL R Series Disc',
          model_variant: 'Endurance SL R Series Disc SRAM Red eTap AXS HRD',
          model_year: 2020,
          brake_type: 'disc',
          image_url: '/images/bicycles/Ribble-Endurance-SL-R-Series-Disc.png',
          drive_train_type: '',
          includes_powermeter: false,
        },

        {
          id: 5,
          name: 'Specialized-S-Works-Tarmac-SL7-Dura-Ace-Di2',
          price: 11500,
          launch_date: new Date().toISOString(),
          score: 4.85,
          brand_id: 1,
          model_family: 'Tarmac SL7',
          model_variant: 'S-Works Tarmac SL7 DURA ACE DI2',
          model_year: 2020,
          brake_type: 'disc',
          image_url:
            '/images/bicycles/2021-s-works-tarmac-sl7-dura-ace-di2.jpg',
          drive_train_type: 'Shimano Dura-Ace Di2 Disc R9170',
          includes_powermeter: true,
        },
        {
          id: 6,
          name: 'Canyon-Aeroad-CFR-Di2',
          price: 7699,
          launch_date: new Date().toISOString(),
          score: 4.2,
          brand_id: 9,
          model_family: 'Aeroad',
          model_variant: 'Aeroad CFR DURA ACE DI2',
          model_year: 2020,
          brake_type: 'disc',
          image_url:
            '/images/bicycles/2021-Canyon-Aeroad-carbon-aero-road-bike_Canyon-Aeroad-CFR-Disc-Di2-1920x1152.webp',
          drive_train_type: 'Shimano Dura-Ace Di2 Disc R9150',
          includes_powermeter: true,
        },
        {
          id: 7,
          name: 'Trek-Madone-SLR9-Disc',
          price: 11050,
          launch_date: new Date().toISOString(),
          score: 5,
          brand_id: 2,
          model_family: 'Madone',
          model_variant: 'Madone SLR 9 Disc',
          model_year: 2020,
          brake_type: 'disc',
          image_url: '/images/bicycles/Trek-Madone-SLR9-Disc.jpg',
          drive_train_type: 'Shimano Dura-Ace Di2 Disc R9150',
          includes_powermeter: true,
        },
        {
          id: 8,
          name: 'Cervélo-S5-Disc-Dura-Ace-Di2',
          price: 9699,
          launch_date: new Date().toISOString(),
          score: 5,
          brand_id: 6,
          model_family: 'S5',
          model_variant: 'S5 Disc Dura Ace Di2',
          model_year: 2020,
          brake_type: 'disc',
          image_url: '/images/bicycles/2019_s5_disc_black_axs_1.jpg',
          drive_train_type: 'Shimano Dura-Ace Di2 Disc R9150',
          includes_powermeter: false,
        },
        {
          id: 9,
          name: 'Bianchi-Oltre-XR4',
          price: 7700,
          launch_date: new Date().toISOString(),
          score: 4.5,
          brand_id: 4,
          model_family: 'Oltre XR4',
          model_variant: 'Oltre XR4 CV Disc',
          model_year: 2020,
          brake_type: 'disc',
          image_url: '/images/bicycles/bianchi-oltre-xr4-2020-di2.jpg',
          drive_train_type: 'Shimano Ultegra Di2',
          includes_powermeter: false,
        },
      ]);
    });
};
